config/routes.rb
Rails.application.routes.draw do
root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


# delete '/restaurants/:id', to: 'restaurants#destroy'
#     get '/restaurants', to: 'restaurants#index'
#     get '/restaurants/:id', to: 'restaurants#show'
#     get '/restaurants/:id/edit', to: 'restaurants#edit'
#     get '/restaurants/new', to: 'restaurants#new'
#     patch '/restaurants/:id', to: 'restaurants#update'
#     post '/restaurants', to: 'restaurants#create'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  # validates :movie, presence: true
  # validates :list, presence: true
  validates_uniqueness_of :movie_id, scope: :list_id
  validates :comment, length: { minimum: 6 }
end

# class Person < ActiveRecord::Base
#   validates_uniqueness_of :user_name, scope: :account_id
# end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmark = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.list_id = @list.id
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end


end


# def new
#     @list = List.new
#   end

#   def create
#     @list = List.new(list_params)
#     if @list.save
#       redirect_to list_path(@list)
#     else
#       render :new
#     end
#   end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= link_to 'Back', root_path %>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Show all movie lists</h1>
<% @lists.each do |list|  %>
<p><%= list.name %></p>
<% end  %>

<%= link_to "Create New List", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= link_to 'Back', root_path %>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h2>My list</h2>
<%= @list.name %>

<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit “Submit comment”, class: “btn btn-primary” %>
<% end %>

<% @list.movies.each do |movie| %>
  <li><%= movie.title %></li>
<% end %>